import { Option } from "@/components/ui/multiple-selector";

export const TECHNOLOGY_OPTIONS: Option[] = [
  { label: "nextjs", value: "Nextjs" },
  { label: "Vite", value: "vite" },
  { label: "Nuxt", value: "nuxt" },
  { label: "Vue", value: "vue, " },
  { label: "Remix", value: "remix" },
  { label: "Svelte", value: "svelte" },
  { label: "Angular", value: "angular" },
  { label: "Ember", value: "ember" },
  { label: "React", value: "react" },
  { label: "Gatsby", value: "gatsby" },
  { label: "Astro", value: "astro" },
];

export const TAG_OPTIONS: Option[] = [
  { label: "Web Development", value: "web-development" },
  { label: "Machine Learning", value: "machine-learning" },
  { label: "Artificial Intelligence", value: "artificial-intelligence" },
  { label: "Cloud Computing", value: "cloud-computing" },
  { label: "Data Science", value: "data-science" },
  { label: "Blockchain", value: "blockchain" },
  { label: "Cybersecurity", value: "cybersecurity" },
  { label: "Mobile Development", value: "mobile-development" },
  { label: "DevOps", value: "devops" },
  { label: "E-commerce", value: "e-commerce" },
  { label: "SaaS", value: "saas" },
  { label: "UI/UX Design", value: "ui-ux-design" },
  { label: "Open Source", value: "open-source" },
  { label: "Digital Marketing", value: "digital-marketing" },
  { label: "Tech News", value: "tech-news" },
  { label: "Startups", value: "startups" },
  { label: "Productivity", value: "productivity" },
  { label: "Software Engineering", value: "software-engineering" },
  { label: "Agile", value: "agile" },
  { label: "Entrepreneurship", value: "entrepreneurship" },
  { label: "Gaming", value: "gaming" },
];

export const CATEGORY_OPTIONS = [
  "Technology",
  "Health",
  "Education",
  "Business",
  "Entertainment",
  "Lifestyle",
  "Science",
  "Travel",
  "Finance",
  "Food",
  "Sports",
  "Politics",
  "Art",
  "Music",
  "Environment",
  "Social Issues",
  "Books",
  "Movies",
  "Gaming",
];
